name: CI
on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0'
jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          override: true
      - name: Cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --all
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sanitizer:
          - thread
          - memory
          - address
          - leak
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          components: rust-src
          override: true
      - name: Get Rust target
        id: target
        run: echo "::set-output name=value::$(basename $(dirname $(rustc --print target-libdir)))"
      - name: Cargo test
        uses: actions-rs/cargo@v1
        env:
          RUSTFLAGS: -Z sanitizer=${{ matrix.sanitizer }}
          RUSTDOCFLAGS: -Z sanitizer=${{ matrix.sanitizer }}
        with:
          command: test
          args: --all --all-features -Z build-std --target ${{ steps.target.outputs.value }}
  miri:
    name: Miri
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          components: miri
          override: true
      - name: Cargo miri setup
        uses: actions-rs/cargo@v1
        with:
          command: miri
          args: setup
      - name: Cargo miri test
        uses: actions-rs/cargo@v1
        with:
          command: miri
          args: test --all --all-features
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          components: clippy, rustfmt
          override: true
      - name: Cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - name: Cargo doc
        uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --workspace --no-deps
      - name: Cargo clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all --tests -- -D warnings
